---
include:
  - board: teal_sofle_right
    shield: nice_view_adapter nice_view_gem
  - board: teal_sofle_left
    shield: nice_view_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: teal_sofle_left
    shield: settings_reset
