---
include:
  - board: teal_sofle_right
    shield: nice-view-gem
  - board: teal_sofle_left
    shield: nice-view-gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: teal_sofle_left
    shield: settings_reset
